### ISSUE TITLE
Your Ruby version is 2.2.3, but your Gemfile specified 2.2.2

### ISSUE THREAD

**Issue by chrise86** [aripollak/rbenv-bundler-ruby-version#10]
Completed all setup instructions but am still getting the following when running `bundle`:

    Your Ruby version is 2.2.3, but your Gemfile specified 2.2.2

**Comment by aripollak** [comment]
What does `rbenv system` say? Can you attach your Gemfile?

**Comment by aripollak** [comment]
I believe I fixed this in 67c64e3cd9.

**Comment by chrise86** [comment]
Sorry for delay, yes it does seem to be fixed, thanks! :)
