### ISSUE TITLE
Whitespace Issue

### ISSUE THREAD

**Issue by juliogarciag** [aripollak/rbenv-bundler-ruby-version#16]
This doesn't work:

``` ruby
ruby    "2.3.0"
```

But this works:

``` ruby
ruby "2.3.0"
```

It would be awesome if the whitespace between `ruby` string and the version string could have more than 1 character. Thanks for this plugin!

**Comment by aripollak** [comment]
Oh yeah, that's just an oversight. Want to submit a pull request?

**Comment by aripollak** [comment]
Fixed in efa2319b69.
