### ISSUE TITLE
Feature Request: Optionally invoke bundler to determine ruby version

### ISSUE THREAD

**Issue by jasonkarns** [aripollak/rbenv-bundler-ruby-version#19]
It would be awesome to be able to invoke bundler to fully and completely parse the ruby version from Gemfile. Since this would be a performance hit (to spin up ruby and bundler), this feature should be opt-in (perhaps via an environment variable?).

Doing so would eliminate the gaps between the version expressions that rbenv-bundler-ruby-version parses and that which bundler itself supports.

https://github.com/rbenv/rbenv/issues/1236#issuecomment-610423465

**Comment by aripollak** [comment]
I agree, but there's a chicken-and-egg problem here: how do you know where to find bundler until you know where to find ruby?

**Comment by jasonkarns** [comment]
Agreed. but since bundler is now "bundled" (har har) with Ruby itself, and this feature would be opt-in, I'd say we just assume _a_ bundler is available in PATH.

To expand further on the environment I'll assume this feature applies to:

many users (myself included) still install their `system` ruby with homebrew. Which means that the system ruby is modern enough to have the `bundler` exe in PATH.

In addition to the opt-in env var, we could pre-emptively check that bundler exists in PATH and emit a helpful warning if it doesn't. But any user who opts-in to this feature would already be aware of its special behavior.

**Comment by aripollak** [comment]
Assuming that:
* a recent-enough Ruby is available in PATH
* Bundler is automatically included with Ruby (which it isn't by default on many systems, like Debian)
* whatever version of Bundler installed system-wide recognizes all possible formats of Ruby version strings

I think we'd still need to do some caching to ensure the selection is fast, so we're not actually running Ruby/Bundler every time we have to choose a Ruby.

**Comment by aripollak** [comment]
I don't plan to implement this, so closing as won't fix.
