### ISSUE TITLE
rbenv ruby-version reporting incorrect version

### ISSUE THREAD

**Issue by joshuacronemeyer** [aripollak/rbenv-bundler-ruby-version#5]
I notice the ruby-version command reports the global ruby version when I use this plugin although ruby -v tells the real story. I have a fancy zsh prompt that tells me what version of ruby is in use, but since i started using this it's mis-reporting. I know plugins can't override any of the rbenv commands but was wondering if you had any ideas about this.

**Comment by jasonkarns** [comment]
can this be reopened for tracking? it's still an issue, even if there isn't (presently) a known fix

**Comment by aripollak** [comment]
@jasonkarns Sorry, I don't think it's particularly useful to me as the maintainer to keep an issue open where the problem is known but the fix is not possible without changes to other software.
